name: Run linter and tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Lint with RuboCop
        run: bin/rubocop --parallel --format tap
      - name: Test with RSpec
        run: bin/rspec
